Xilinx RoE Application: Sample_app
Sample_app
Functions
int main (int argc, char **argv)
Macro Definition Documentation
#define ECPRI_STR "eCPRI commands\n"
ECPRI_STR Help text for "ecpri" command.
#define IP_STR "Raw IP memory device access\n"
IP_STR Help text for "ip" command.
#define PID_FILE "/var/run/xroe.pid"
PID_FILE The full name of the file containing the application process id.
Referenced by main().
#define RADIO_CTRL_STR "Radio control device access\n"
RADIO_CTRL_STR Help text for "radio" command.
#define STATS_STR "Stats device access\n"
STATS_STR Help text for "stats" command.
#define XROE_DISABLE_STR "Disable framer/deframer\n"
XROE_DISABLE_STR Help text for "disable" command.
#define XROE_ENABLE_STR "Enable framer/deframer\n"
XROE_ENABLE_STR Help text for "enable" command.
#define XROE_FRAM_STR "Framer/deframer control commands\n"
XROE_FRAM_STR Help text for "framing" command.
#define XROE_HELP_STR "generates this list of commands\n"
XROE_HELP_STR Help text for "help" command.
#define XROE_QUIT_STR "Received quit command, exiting\n"
XROE_QUIT_STR Response string for quit command.
Referenced by parse_command().
#define XROE_RESTART_STR "XXV Reset\n"
XROE_RESTART_STR Help text for "restart" command.
#define XROE_USAGE_STR
Value:
"Xilinx Radio Over Ethernet Framer Application (xroe-app)\n" \
__DATE__ " " __TIME__ "\n" \
"Usage: <app> [options] [\"command [args]\"]\n" \
"Options:\n" \
"  -d daemonise server\n" \
"  -s soft server mode, no local hardware\n" \
"  -c send command to server\n" \
"  -n <ip_addr> with -c send command to remote app at <ip_addr>\n" \
"  -p <port> with -n specifies remote port to send to, with -d or -s specifies server listen port\n" \
"  -h produces this help\n" \
"\n" \
"Commands:\n" \
"  <command> [args]\n" \
"Try: <app> [-n <ip_addr> [-p <port>]] -c \"help\" for list of server commands\n"
XROE_USAGE_STR Help text for the application, listing command line options.
Referenced by main(), and parse_command().
#define XROE_VER_STR "Not yet supported\n"
XROE_VER_STR Help text for "version" command.
Referenced by version_func().
Function Documentation
int main (int argc, char ** argv)
Entry point into sample application Parses optional arguments, opens connections and log, contains the message handling loop.
argc less than 2 (i.e. just calling the program with no command-line arguments), or the first command line argument being "help" will return the help text. Other valid options are:
d: daemonise the application
s: soft mode, do not open UNIX socket or UDP socket for eCPRI messages
n: connect to remote application at given IP address (requires -c)
p: connect to given remote port (-c) or listen on the given port
c: send command to listening application (UNIX socket by default)
Parameters
[in] argc Number of command-line arguments (including program name)
[in] argv Array of strings containg command-line arguments
Returns
EXIT_SUCCESS on clean exit
EXIT_FAILURE on start-up error
References client_send_message(), close_connections(), get_message(), MAX_RESPONSE_LENGTH, open_connections(), parse_command(), PID_FILE, send_response(), and XROE_USAGE_STR.