Xilinx RoE Application: Framer_driver_api
Framer_driver_api
Functions
int IP_API_Read (int addr, uint8_t *pRead, int length)
int IP_API_Write (int addr, uint8_t *pWrite, int length)
int IP_API_Read_Register (int addr, unsigned int *pRead, int Mask, int Offset)
int IP_API_Write_Register (int addr, unsigned int Write, int Mask, int Offset)
int STATS_API_Read_Register (int addr, unsigned int *pRead)
int FRAMER_API_Framer_Restart (int restart)
int FRAMER_API_Deframer_Restart (int restart)
int RADIO_CTRL_API_Read (int addr, uint8_t *pRead, int length)
int RADIO_CTRL_API_Write (int addr, uint8_t *pWrite, int length)
int RADIO_CTRL_API_Read_Register (int addr, unsigned int *pRead, int Mask, int Offset)
int RADIO_CTRL_API_Write_Register (int addr, unsigned int value, int Mask, int Offset)
int XXV_API_Reset (void)
Function Documentation
int FRAMER_API_Deframer_Restart (int restart)
Enables or disables the deframer.
Writes true or false to deframer restart sysfs variable to enable or disable the deframer.
Parameters
[in] restart Non-zero to disable (assert restart), zero to enable
Returns
0 on success
-1 on device open failure
EFAULT on write() failure
Referenced by disable_deframer_func(), and enable_deframer_func().
int FRAMER_API_Framer_Restart (int restart)
Enables or disables the framer.
Writes true or false to framer restart sysfs variable to enable. or disable the framer
Parameters
[in] restart Non-zero to disable (assert restart), zero to enable
Returns
0 on success
-1 on device open failure
EFAULT on write() failure
Referenced by disable_framer_func(), and enable_framer_func().
int IP_API_Read (int addr, uint8_t * pRead, int length)
Reads bytes from anywhere in the framer address space.
Reads bytes from the address given and writes them into pRead.
Parameters
[in] addr Address in framer address space (0 base) to read from
[out] pRead Pointer to use to store output
[in] length Number of bytes to read
Returns
0 on success
EIO on device open failure
EFAULT on pread() failure
Referenced by framing_get_defr_func(), framing_get_fram_func(), framing_set_defr_func(), framing_set_fram_func(), ip_peek_func(), and proto_ecpri_handle_incoming_rma().
int IP_API_Read_Register (int addr, unsigned int * pRead, int Mask, int Offset)
Reads 32-bits from anywhere in the framer address space.
Reads 32-bits from the address given, shifts and masks them as per Offset and Mask, and writes them into pRead.
Parameters
[in] addr Address in framer address space (0 base) to read from
[out] pRead Pointer to use to store output
[in] Mask Mask to use to mask output before shifting
[in] Offset Number of bits to shift output down by after masking
Returns
0 on success
EIO on device open failure
EFAULT on pread() failure
Referenced by RADIO_CTRL_CalulateBufStateLatency(), radio_ctrl_update_values(), and stats_update_values().
int IP_API_Write (int addr, uint8_t * pWrite, int length)
Writes bytes to anywhere in the framer address space.
Writes length bytes to addr from pWrite.
Parameters
[in] addr Address in framer address space (0 base) to write to
[in] pWrite Pointer to read from
[in] length Number of bytes to write
Returns
0 on success
EIO on device open failure
EFAULT on pwrite() failure
Referenced by framing_set_defr_func(), framing_set_fram_func(), ip_poke_func(), and proto_ecpri_handle_incoming_rma().
int IP_API_Write_Register (int addr, unsigned int Write, int Mask, int Offset)
Writes 32-bits to anywhere in the framer address space.
Writes 32-bits from Write to the address given, after shifting and masking them as per Offset and Mask.
Parameters
[in] addr Address in framer address space (0 base) to write to
[in] Write Value to write
[in] Mask Mask to use to mask input after shifting
[in] Offset Number of bits to shift input up by before masking
Returns
0 on success
EIO on device open failure
EFAULT on pwrite() failure
int RADIO_CTRL_API_Read (int addr, uint8_t * pRead, int length)
Reads bytes from anywhere in the radio_ctrl address space.
Reads bytes from the address given and writes them into pRead.
Parameters
[in] addr Address in radio_ctrl address space (0 base) to read from
[out] pRead Pointer to use to store output
[in] length Number of bytes to read
Returns
0 on success
EIO on device open failure
EFAULT on pread() failure
Referenced by proto_ecpri_handle_incoming_rma(), RADIO_CTRL_API_Read_Register(), and radio_ctrl_peek_func().
int RADIO_CTRL_API_Read_Register (int addr, unsigned int * pRead, int Mask, int Offset)
Reads 32-bits from anywhere in the radio_ctrl address space.
Reads 32-bits from addr to pRead, shifted and masked as per Offset and Mask.
Parameters
[in] addr Address in radio_ctrl address space (0 base) to read from
[in] pRead Pointer to use to store output
[in] Mask Mask to use to mask output before shifting
[in] Offset Number of bits to shift output down by after masking
Returns
0 on success
EIO on device open failure
EFAULT on pread() failure
References RADIO_CTRL_API_Read().
Referenced by RADIO_CTRL_API_Write_Register(), radio_ctrl_radio_id_func(), and radio_ctrl_update_values().
int RADIO_CTRL_API_Write (int addr, uint8_t * pWrite, int length)
Writes bytes to anywhere in the radio_ctrl address space.
Writes length bytes from pWrite to addr.
Parameters
[in] addr Address in radio_ctrl address space (0 base) to write to
[in] pWrite Pointer to read from
[in] length Number of bytes to write
Returns
0 on success
EIO on device open failure
EFAULT on pwrite() failure
Referenced by proto_ecpri_handle_incoming_rma(), RADIO_CTRL_API_Write_Register(), and radio_ctrl_poke_func().
int RADIO_CTRL_API_Write_Register (int addr, unsigned int value, int Mask, int Offset)
Writes 32-bits to anywhere in the radio_ctrl address space.
Performs a Read/Modify/Write of 32-bits from pWrite to addr, shifted and masked as per Offset and Mask.
Parameters
[in] addr Address in radio_ctrl address space (0 base) to write to
[in] value Value to write
[in] Mask Mask to use to mask input after shifting
[in] Offset Number of bits to shift input up by before masking
Returns
0 on success
EIO on device open failure
EFAULT on pwrite() failure
References RADIO_CTRL_API_Read_Register(), and RADIO_CTRL_API_Write().
Referenced by ecpri_owdm_calc_delay(), radio_ctrl_loopback_dis_func(), and radio_ctrl_loopback_en_func().
int STATS_API_Read_Register (int addr, unsigned int * pRead)
Reads 32-bits from the stats address space.
Reads 32-bits from the address given and writes them into pRead.
Parameters
[in] addr Address in stats address space (0 base) to read from
[out] pRead Pointer to use to store output
Returns
0 on success
EIO on device open failure
EFAULT on ioctl() failure
Referenced by stats_hw_func(), and stats_update_values().
int XXV_API_Reset (void)
Resets the XXV Ethernet interface.
Asserts then de-asserts the XXV Ethernet reset.
Returns
0 on success
-1 on device open failure
EFAULT on write() failure
Referenced by restart_xxv_func().