Xilinx RoE Application: Command_parser
Command_parser
Functions
int help_func (int argc, char **argv, char *resp)
int ecpri_func (int argc, char **argv, char *resp)
int ip_func (int argc, char **argv, char *resp)
int stats_func (int argc, char **argv, char *resp)
int version_func (int argc, char **argv, char *resp)
int enable_func (int argc, char **argv, char *resp)
int disable_func (int argc, char **argv, char *resp)
int framing_func (int argc, char **argv, char *resp)
int restart_func (int argc, char **argv, char *resp)
int radio_ctrl_func (int argc, char **argv, char *resp)
int disable_help_func (int argc, char **argv, char *resp)
int disable_framer_func (int argc, char **argv, char *resp)
int disable_deframer_func (int argc, char **argv, char *resp)
int ecpri_help_func (int argc, char **argv, char *resp)
int ecpri_owdm_req_func (int argc, char **argv, char *resp)
int ecpri_owdm_res_func (int argc, char **argv, char *resp)
int ecpri_owdm_limit_func (int argc, char **argv, char *resp)
int ecpri_rma_read_func (int argc, char **argv, char *resp)
int ecpri_rma_write_func (int argc, char **argv, char *resp)
int ecpri_test_mesg_func (int argc, char **argv, char *resp)
int ecpri_rmr_req_func (int argc, char **argv, char *resp)
int owdm_send_request (uint8_t type, char *dest_addr)
int rma_send_request (int type, char *dest_addr, char *addr, char *length, char *values)
int test_mesg_send_request (char *dest_addr, char *dest_port)
int rma_get_response (int type, char *addr, int *length, char **values)
int rmr_send_request (char *dest_addr)
int rmr_get_response (char *addr, char **values)
int enable_help_func (int argc, char **argv, char *resp)
int enable_framer_func (int argc, char **argv, char *resp)
int enable_deframer_func (int argc, char **argv, char *resp)
int framing_help_func (int argc, char **argv, char *resp)
int framing_set_fram_func (int argc, char **argv, char *resp)
int framing_get_fram_func (int argc, char **argv, char *resp)
int framing_set_defr_func (int argc, char **argv, char *resp)
int framing_get_defr_func (int argc, char **argv, char *resp)
int ip_help_func (int argc, char **argv, char *resp)
int ip_peek_func (int argc, char **argv, char *resp)
int ip_poke_func (int argc, char **argv, char *resp)
int tokenise_input (char *in_str, char **cmd_tokens)
int parse_command (int nohw, char *command, char *response)
int RADIO_CTRL_CalulateBufStateLatency (int index, unsigned int *pBufStateLatency)
int radio_ctrl_update_values (void)
int radio_ctrl_help_func (int argc, char **argv, char *resp)
int radio_ctrl_radio_id_func (int argc, char **argv, char *resp)
int radio_ctrl_status_func (int argc, char **argv, char *resp)
int radio_ctrl_loopback_en_func (int argc, char **argv, char *resp)
int radio_ctrl_loopback_dis_func (int argc, char **argv, char *resp)
int radio_ctrl_gui_func (int argc, char **argv, char *resp)
int radio_ctrl_peek_func (int argc, char **argv, char *resp)
int radio_ctrl_poke_func (int argc, char **argv, char *resp)
int restart_help_func (int argc, char **argv, char *resp)
int restart_xxv_func (int argc, char **argv, char *resp)
int stats_help_func (int argc, char **argv, char *resp)
int stats_hw_func (int argc, char **argv, char *resp)
int stats_sw_func (int argc, char **argv, char *resp)
int stats_user_func (int argc, char **argv, char *resp)
int stats_ctrl_func (int argc, char **argv, char *resp)
int stats_rate_func (int argc, char **argv, char *resp)
int stats_all_func (int argc, char **argv, char *resp)
int stats_all_gui_func (int argc, char **argv, char *resp)
int stats_update_values (void)
Macro Definition Documentation
#define DISABLE_DEFRAMER_STR "Disables the Deframer\n"
DISABLE_USAGE_STR Help text for the disable module "deframer" option.
#define DISABLE_FRAMER_STR "Disables the Framer\n"
DISABLE_FRAMER_STR Help text for the disable module "framer" option.
#define DISABLE_HELP_STR "generates this list of commands\n"
DISABLE_HELP_STR Help text for the disable module "help" option.
#define DISABLE_MAX_COMMANDS 4
DISABLE_MAX_COMMANDS Number of commands handled by the disable module.
#define DISABLE_USAGE_STR "Usage \"disable <options>\", try \"disable help\" for command list\n"
DISABLE_USAGE_STR Help text for the disable module.
Referenced by disable_func().
#define ECPRI_HELP_STR "generates this list of commands\n"
ECPRI_HELP_STR Help text for the ecpri module "help" option.
#define ECPRI_MAX_COMMANDS 9
ECPRI_MAX_COMMANDS Number of commands handled by the ecpri module.
#define ECPRI_OWDM_LIMIT_STR "ecpri owdm_limit - Sets the report threshold of the OWDM measurement (nsecs), or disables reporting if 0\n"
ECPRI_OWDM_LIMIT_STR Help text for the ecpri module "owdm_limit" option.
Referenced by ecpri_owdm_limit_func().
#define ECPRI_OWDM_REQ_STR "ecpri owdm_req <addr> <type> - Request an OWDM measurement to <addr> of type <to_remote|from_remote>\n"
ECPRI_OWDM_REQ_STR Help text for the ecpri module "owdm_req" option.
Referenced by ecpri_owdm_req_func().
#define ECPRI_OWDM_RES_STR "ecpri owdm_res - Returns the result of the last OWDM measurement, or \"Pending\" if still underway\n"
ECPRI_OWDM_RES_STR Help text for the ecpri module "owdm_res" option.
Referenced by ecpri_owdm_res_func().
#define ECPRI_RMA_READ_STR "ecpri rma_read <ip_addr> <mem_addr> <length> - Request a read of <length> bytes at <mem_addr> from <ip_addr>\n"
ECPRI_RMA_READ_STR Help text for the ecpri module "rma_read" option.
Referenced by ecpri_rma_read_func().
#define ECPRI_RMA_WRITE_STR "ecpri rma_write <ip_addr> <mem_addr> <length> \"<bytes 1..length>\" - Request a write of <length> <bytes> to <mem_addr> at <ip_addr>\n"
ECPRI_RMA_WRITE_STR Help text for the ecpri module "rma_write" option.
Referenced by ecpri_rma_write_func().
#define ECPRI_RMR_REQ_STR "ecpri rmr_req <ip_addr> - Request a remote reset of <ip_addr>\n"
ECPRI_RMR_REQ_STR Help text for the ecpri module "rmr_req" option.
Referenced by ecpri_rmr_req_func().
#define ECPRI_TEST_MESG_STR "ecpri test_mesg <ip_addr> <dest_port> - TESTING - Send a test message to <dest_port>\n"
ECPRI_TEST_MESG_STR Help text for the ecpri module "test_mesg" option.
Referenced by ecpri_test_mesg_func().
#define ECPRI_USAGE_STR "Usage \"ecpri [args]\", try \"ecpri help\" for command list\n"
ECPRI_USAGE_STR Help text for the ecpri module.
Referenced by ecpri_func().
#define ENABLE_DEFRAMER_STR "Enables the Deframer\n"
ENABLE_DEFRAMER_STR Help text for the enable module "deframer" option.
#define ENABLE_FRAMER_STR "Enables the Framer\n"
ENABLE_FRAMER_STR Help text for the enable module "framer" option.
#define ENABLE_HELP_STR "generates this list of commands\n"
ENABLE_HELP_STR Help text for the enable module "help" option.
#define ENABLE_MAX_COMMANDS 4
ENABLE_MAX_COMMANDS Number of commands handled by the enable module.
#define ENABLE_USAGE_STR "Usage \"enable <options>\", try \"enable help\" for command list\n"
ENABLE_USAGE_STR Help text for the enable module.
Referenced by enable_func().
#define FRAMING_DEFRAMER_REG_NUM 14
FRAMING_DEFRAMER_REG_NUM Number of registers valid for deframer commands.
Referenced by framing_get_defr_func().
#define FRAMING_DEFRAMER_WR_REG_NUM 2
FRAMING_DEFRAMER_WR_REG_NUM Number of registers valid for deframer writes.
Referenced by framing_set_defr_func().
#define FRAMING_FRAMER_REG_NUM 6
FRAMING_FRAMER_REG_NUM Number of registers valid for framer commands.
Referenced by framing_get_fram_func(), and framing_set_fram_func().
#define FRAMING_MAX_COMMANDS 6
FRAMING_MAX_COMMANDS Number of commands handled by the framing module.
#define FRAMING_MAX_REG_NAME_LENGTH 16
FRAMING_MAX_REG_NAME_LENGTH Macimum length of a register name.
#define FRAMING_REG_SIZE 4
FRAMING_REG_SIZE Sizee in bytes of framer/deframer registers.
Referenced by framing_get_defr_func(), framing_get_fram_func(), framing_set_defr_func(), and framing_set_fram_func().
#define IP_HELP_STR "generates this list of ip subcommands\n"
IP_HELP_STR Help text for the IP module "help" option.
#define IP_MAX_COMMANDS 4
IP_MAX_COMMANDS Number of commands handled by the IP module.
#define IP_PEEK_STR "ip peek <address>\n"
IP_PEEK_STR Help text for the IP module "peek" option.
Referenced by ip_peek_func().
#define IP_POKE_STR "ip poke <address> <value>\n"
IP_POKE_STR Help text for the IP module "poke" option.
Referenced by ip_poke_func().
#define IP_USAGE_STR "Usage is \"ip <command> <address> [value]\", try \"ip help\" for command list\n"
IP_USAGE_STR Help text for the enable module.
Referenced by ip_func().
#define MAX_NUMBER_OF_ANTENNAS 8
MAX_NUMBER_OF_ANTENNAS Number of antennae supported by the radio_ctrl module.
Referenced by RADIO_CTRL_CalulateBufStateLatency(), radio_ctrl_gui_func(), radio_ctrl_status_func(), and radio_ctrl_update_values().
#define MAX_NUMBER_TOKENS 10
MAX_NUMBER_TOKENS Maximum number of tokens a command string may contain.
Referenced by parse_command(), and tokenise_input().
#define RADIO_CTRL_GUI_STR "[DEV] all radio output for GUI\n"
RADIO_CTRL_GUI_STR Help text for the radio_ctrl module "gui" option.
#define RADIO_CTRL_HELP_STR "generates this list of commands\n"
RADIO_CTRL_HELP_STR Help text for the radio_ctrl module "help" option.
#define RADIO_CTRL_LOOPBACK_DIS_STR "Disables the loopback\n"
RADIO_CTRL_LOOPBACK_DIS_STR Help text for the radio_ctrl module "loopback_dis" option.
#define RADIO_CTRL_LOOPBACK_EN_STR "Enables the loopback\n"
RADIO_CTRL_LOOPBACK_EN_STR Help text for the radio_ctrl module "loopback_en" option.
#define RADIO_CTRL_PEEK_STR "radio_ctrl peek <address>\n"
RADIO_CTRL_PEEK_STR Help text for the radio_ctrl module "peek" option.
Referenced by radio_ctrl_peek_func().
#define RADIO_CTRL_POKE_STR "radio_ctrl poke <address> <value>\n"
RADIO_CTRL_POKE_STR Help text for the radio_ctrl module "poke" option.
Referenced by radio_ctrl_poke_func().
#define RADIO_CTRL_RADIO_ID_STR "[DEV] Returns the Radio ID tag\n"
RADIO_CTRL_RADIO_ID_STR Help text for the radio_ctrl module "id" option.
#define RADIO_CTRL_STATUS_STR "Returns the enable, error, status and loopback\n"
RADIO_CTRL_STATUS_STR Help text for the radio_ctrl module "status" option.
#define RADIO_CTRL_USAGE_STR "Usage \"radio_ctrl <options>\", try \"radio_ctrl help\" for command list\n"
RADIO_CTRL_USAGE_STR Help text for the radio_ctrl module.
Referenced by radio_ctrl_func().
#define RADIO_MAX_COMMANDS 9
RADIO_MAX_COMMANDS Number of commands handled by the radio_ctrl module.
#define RESTART_HELP_STR "generates this list of commands\n"
RESTART_HELP_STR Help text for the restart module "help" option.
#define RESTART_MAX_COMMANDS 4
RESTART_MAX_COMMANDS Number of commands handled by the restart module.
#define RESTART_USAGE_STR "Usage \"restart <options>\", try \"restart help\" for command list\n"
RESTART_USAGE_STR Help text for the restart module.
Referenced by restart_func().
#define RESTART_XXV_RESET_STR "XXV_Reset\n"
RESTART_XXV_RESET_STR Help text for the restart module "xxv" option.
#define RMA_READ 1
RMA_READ Flag to indicate an RMA read operation.
Referenced by ecpri_rma_read_func(), rma_get_response(), and rma_send_request().
#define RMA_WRITE 2
RMA_WRITE Flag to indicate an RMA write operation.
Referenced by ecpri_rma_write_func().
#define STATS_ALL_STR "Returns a summary of all stats\n"
STATS_ALL_STR Help text for the stats module "all" option.
#define STATS_CTRL_STR "Returns control packets stats\n"
STATS_CTRL_STR Help text for the stats module "control" option.
#define STATS_DEV_NUM_STR "[DEV] get the internal revision number of the stats device\n"
STATS_DEV_NUM_STR Help text for the stats module "rev" option.
#define STATS_GUI_NUM_STR "[DEV] all stats output for GUI\n"
STATS_GUI_NUM_STR Help text for the stats module "gui" option.
#define STATS_HELP_STR "generates this list of commands\n"
STATS_HELP_STR Help text for the stats module "help" option.
#define STATS_HW_STR "\"stats hw <address>\". Reads statistic at address\n"
STATS_HW_STR Help text for the stats module "hw" option.
Referenced by stats_hw_func().
#define STATS_MAX_COMMANDS 10
STATS_MAX_COMMANDS Number of commands handled by the stats module.
#define STATS_RATE_STR "Returns packet rate stats\n"
STATS_RATE_STR Help text for the stats module "rate" option.
#define STATS_SW_STR "Software statistics not supported\n"
STATS_SW_STR Help text for the stats module "sw" option.
Referenced by stats_sw_func().
#define STATS_USAGE_STR "Usage \"stats <options>\", try \"stats help\" for command list\n"
STATS_USAGE_STR Help text for the stats module.
Referenced by stats_func().
#define STATS_USER_STR "Returns user data packets stats\n"
STATS_USER_STR Help text for the stats module "user" option.
#define XROE_MAX_COMMANDS 11
XROE_MAX_COMMANDS Number of commands handled at the top level.
Referenced by help_func().
Typedef Documentation
typedef struct antennas_status_struct antennas_status_struct
antennas_status_struct Status values for an antenna array.
typedef struct packets_struct packets_struct
packets_struct Packet type count.
typedef struct radio_ctrl_struct radio_ctrl_struct
radio_ctrl_struct Control/status structure for the radio.
typedef struct single_antenna_status_struct single_antenna_status_struct
single_antenna_status_struct Status values for an antenna.
typedef struct stats_struct stats_struct
stats_struct Statistics structure.
typedef struct total_packets_struct total_packets_struct
total_packets_struct Totals packets count.
Function Documentation
int disable_deframer_func (int argc, char ** argv, char * resp)
Disables the deframer by setting the restart value high.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
Return value of FRAMER_API_Deframer_Restart()
References FRAMER_API_Deframer_Restart().
int disable_framer_func (int argc, char ** argv, char * resp)
Disables the framer by setting the restart value high.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
Return value of FRAMER_API_Framer_Restart()
References FRAMER_API_Framer_Restart().
int disable_func (int argc, char ** argv, char * resp)
Parses the input command string and calls a handler function (if found).
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
1 if no commands tokens found.
2 if no handler found for command.
0 otherwise.
References disable_cmds, and DISABLE_USAGE_STR.
int disable_help_func (int argc, char ** argv, char * resp)
Returns help strings for disable commands.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References disable_cmds.
int ecpri_func (int argc, char ** argv, char * resp)
Parses the input command string and calls a handler function (if found).
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
1 if no commands tokens found.
2 if no handler found for command.
0 otherwise.
References ecpri_cmds, and ECPRI_USAGE_STR.
int ecpri_help_func (int argc, char ** argv, char * resp)
Returns help strings for eCPRI commands.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References ecpri_cmds.
int ecpri_owdm_limit_func (int argc, char ** argv, char * resp)
Sets the reporting limit of the latest One-Way Delay Measurement.
This function calls the eCPRI protocol module to set the limit. If the specified threshold value is 0, reporting is disabled, otherwise all OWDM measurements over the limit (in nsecs) trigger an ILA write.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References ECPRI_OWDM_LIMIT_STR, and proto_ecpri_set_owdm_limit().
int ecpri_owdm_req_func (int argc, char ** argv, char * resp)
Requests a One-Way Delay Measurement to/from a remote node.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References ECPRI_OWDM_MSG_ACTION_REM_REQ_FOL_UP, ECPRI_OWDM_MSG_ACTION_REQ_FOL_UP, ECPRI_OWDM_REQ_STR, and owdm_send_request().
int ecpri_owdm_res_func (int argc, char ** argv, char * resp)
Gets the result of the latest One-Way Delay Measurement.
This function calls the eCPRI protocol module to retrieve the result.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References ECPRI_OWDM_RES_STR, proto_ecpri_get_owdm_result(), and TO_REMOTE.
int ecpri_rma_read_func (int argc, char ** argv, char * resp)
Requests a Remote Memory read from a remote node.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References ECPRI_RMA_READ_STR, rma_get_response(), RMA_READ, and rma_send_request().
int ecpri_rma_write_func (int argc, char ** argv, char * resp)
Requests a Remote Memory write to a remote node.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References ECPRI_RMA_WRITE_STR, rma_get_response(), rma_send_request(), and RMA_WRITE.
int ecpri_rmr_req_func (int argc, char ** argv, char * resp)
Requests a Remote Reset of a remote node.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References ECPRI_RMR_REQ_STR, rmr_get_response(), and rmr_send_request().
int ecpri_test_mesg_func (int argc, char ** argv, char * resp)
Sends a test message (generic data) to a remote node.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References ECPRI_TEST_MESG_STR, and test_mesg_send_request().
int enable_deframer_func (int argc, char ** argv, char * resp)
Enables the deframer by setting the restart value low.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
Return value of FRAMER_API_Deframer_Restart()
References FRAMER_API_Deframer_Restart().
int enable_framer_func (int argc, char ** argv, char * resp)
Enables the framer by setting the restart value low.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
Return value of FRAMER_API_Framer_Restart()
References FRAMER_API_Framer_Restart().
int enable_func (int argc, char ** argv, char * resp)
Parses the input command string and calls a handler function (if found).
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
1 if no commands tokens found.
2 if no handler found for command.
0 otherwise.
References enable_cmds, and ENABLE_USAGE_STR.
int enable_help_func (int argc, char ** argv, char * resp)
Returns help strings for enable commands.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References enable_cmds.
int framing_func (int argc, char ** argv, char * resp)
Parses the input command string and calls a handler function (if found).
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
1 if no commands tokens found.
2 if no handler found for command.
0 otherwise.
References framing_cmds.
int framing_get_defr_func (int argc, char ** argv, char * resp)
Gets field from framing register.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0 Success
1 Not enough arguments
2 Register field not found
References FRAMING_DEFRAMER_REG_NUM, FRAMING_REG_SIZE, and IP_API_Read().
int framing_get_fram_func (int argc, char ** argv, char * resp)
Gets field from framing register.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0 Success
1 Not enough arguments
2 Register field not found
References FRAMING_FRAMER_REG_NUM, FRAMING_REG_SIZE, and IP_API_Read().
int framing_help_func (int argc, char ** argv, char * resp)
Returns help strings for framing commands.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References framing_cmds.
int framing_set_defr_func (int argc, char ** argv, char * resp)
Sets field in deframing register.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0 Success
1 Not enough arguments
2 Register field not found
References FRAMING_DEFRAMER_WR_REG_NUM, FRAMING_REG_SIZE, IP_API_Read(), and IP_API_Write().
int framing_set_fram_func (int argc, char ** argv, char * resp)
Sets field in framing register.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0 Success
1 Not enough arguments
2 Register field not found
References FRAMING_FRAMER_REG_NUM, FRAMING_REG_SIZE, IP_API_Read(), and IP_API_Write().
int help_func (int argc, char ** argv, char * resp)
Returns help strings for top-level commands.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References cmds, and XROE_MAX_COMMANDS.
int ip_func (int argc, char ** argv, char * resp)
Parses the input command string and calls a handler function (if found).
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
1 if no commands tokens found.
2 if no handler found for command.
0 otherwise.
References ip_cmds, and IP_USAGE_STR.
int ip_help_func (int argc, char ** argv, char * resp)
Returns help strings for IP commands.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References ip_cmds.
int ip_peek_func (int argc, char ** argv, char * resp)
Returns the 32-bits at the given memory address.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References IP_API_Read(), and IP_PEEK_STR.
int ip_poke_func (int argc, char ** argv, char * resp)
Writes the 32-bits given to the given memory address.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References IP_API_Write(), and IP_POKE_STR.
int owdm_send_request (uint8_t type, char * dest_addr)
Sends a One-Way Delay Measurement request to a remote node.
This function calls the eCPRI protocol module to format and send the message.
Parameters
[in] type The direction, either TO_REMOTE or FROM_REMOTE.
[in] dest_addr IP address of remote node.
Returns
0 if address is not valid.
Return value of proto_ecpri_owdm_send_request().
References port_ip, and proto_ecpri_owdm_send_request().
Referenced by ecpri_owdm_req_func().
int parse_command (int nohw, char * command, char * response)
Parses the input command string and calls a lower-level handler (if found).
Parameters
[in] nohw Ignored.
[in] command String of space separated command tokens.
[out] response Pointer to string to place response text in.
Returns
0 if no commands tokens found or no handler for command.
-1 on "quit" command.
Return value of lower-level command handler otherwise.
References cmds, MAX_NUMBER_TOKENS, tokenise_input(), XROE_QUIT_STR, and XROE_USAGE_STR.
Referenced by main().
int RADIO_CTRL_CalulateBufStateLatency (int index, unsigned int * pBufStateLatency)
Calculates the buffer state latency for a given antenna.
Parameters
[in] index Index of the antenna to calculate for.
[out] pBufStateLatency Pointer to place result in.
Returns
-1 if index out of range.
Return value of IP_API_Read_Register() otherwise.
References IP_API_Read_Register(), and MAX_NUMBER_OF_ANTENNAS.
Referenced by radio_ctrl_update_values().
int radio_ctrl_func (int argc, char ** argv, char * resp)
Parses the input command string and calls a handler function (if found).
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
1 if no commands tokens found.
2 if no handler found for command.
0 otherwise.
References radio_ctrl_cmds, and RADIO_CTRL_USAGE_STR.
int radio_ctrl_gui_func (int argc, char ** argv, char * resp)
Gets antennae and radio status in JSON format into resp for GUI display.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References MAX_NUMBER_OF_ANTENNAS, and radio_ctrl_update_values().
int radio_ctrl_help_func (int argc, char ** argv, char * resp)
Returns help strings for radio_ctrl commands.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References radio_ctrl_cmds.
int radio_ctrl_loopback_dis_func (int argc, char ** argv, char * resp)
Disables loopback functionality on the radio module.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References RADIO_CTRL_API_Write_Register().
int radio_ctrl_loopback_en_func (int argc, char ** argv, char * resp)
Enables loopback functionality on the radio module.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References RADIO_CTRL_API_Write_Register().
int radio_ctrl_peek_func (int argc, char ** argv, char * resp)
Returns the 32-bits at the given memory address.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References RADIO_CTRL_API_Read(), and RADIO_CTRL_PEEK_STR.
int radio_ctrl_poke_func (int argc, char ** argv, char * resp)
Writes the 32-bits given to the given memory address.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References RADIO_CTRL_API_Write(), and RADIO_CTRL_POKE_STR.
int radio_ctrl_radio_id_func (int argc, char ** argv, char * resp)
Gets radio ID into resp.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References RADIO_CTRL_API_Read_Register().
int radio_ctrl_status_func (int argc, char ** argv, char * resp)
Gets antennae and radio status in text format into resp.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References MAX_NUMBER_OF_ANTENNAS, and radio_ctrl_update_values().
int radio_ctrl_update_values (void)
Updates the internal radio and antennae status variables.
Returns
Return value of RADIO_CTRL_API_Read_Register() on error.
Return value of IP_API_Read_Register() on error.
Return value of RADIO_CTRL_CalulateBufStateLatency() on error.
Return value of RADIO_CTRL_API_Read_Register() otherwise.
References IP_API_Read_Register(), MAX_NUMBER_OF_ANTENNAS, RADIO_CTRL_API_Read_Register(), and RADIO_CTRL_CalulateBufStateLatency().
Referenced by radio_ctrl_gui_func(), and radio_ctrl_status_func().
int restart_func (int argc, char ** argv, char * resp)
Parses the input command string and calls a handler function (if found).
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
1 if no commands tokens found.
2 if no handler found for command.
0 otherwise.
References restart_cmds, and RESTART_USAGE_STR.
int restart_help_func (int argc, char ** argv, char * resp)
Returns help strings for restart commands.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References restart_cmds.
int restart_xxv_func (int argc, char ** argv, char * resp)
Restarts the XXV Ethernet interface.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
Return value of XXV_API_Reset()
References XXV_API_Reset().
int rma_get_response (int type, char * addr, int * length, char ** values)
Reads a Remote Memory Access response from a remote node.
This function calls the eCPRI protocol module to receive the message.
Parameters
[in] type Can be read or write.
[in] addr Ignored.
[in] length The number of bytes read/written.
[in] values Array of byte values read, or NULL on write.
Returns
Return value of proto_ecpri_rma_get_response().
References ECPRI_RMA_MSG_READ, ECPRI_RMA_MSG_WRITE, proto_ecpri_rma_get_response(), and RMA_READ.
Referenced by ecpri_rma_read_func(), and ecpri_rma_write_func().
int rma_send_request (int type, char * dest_addr, char * addr, char * length, char * values)
Sends a Remote Memory Access request to a remote node.
This function calls the eCPRI protocol module to format and send the message.
Parameters
[in] type Can be read or write.
[in] dest_addr IP address of remote node.
[in] addr The remote memory address to access.
[in] length The number of bytes to access.
[in] values Array of byte values to write, or NULL on read.
Returns
-1 if malloc failed.
0 if address is not valid.
Return value of proto_ecpri_rma_send_request().
References ECPRI_RMA_MSG_READ, ECPRI_RMA_MSG_WRITE, port_ip, proto_ecpri_rma_send_request(), and RMA_READ.
Referenced by ecpri_rma_read_func(), and ecpri_rma_write_func().
int rmr_get_response (char * addr, char ** values)
Gets a Remote Reset response from a remote node.
This function calls the eCPRI protocol module to receive the message.
Parameters
[in] addr Address of the remote node to reset.
[out] values Pointer to string to place the response into.
Returns
Return value of proto_ecpri_rmr_get_response().
References proto_ecpri_rmr_get_response().
Referenced by ecpri_rmr_req_func().
int rmr_send_request (char * dest_addr)
Sends a Remote Reset request to a remote node.
This function calls the eCPRI protocol module to format and send the message.
Parameters
[in] dest_addr Address of the remote node to reset.
Returns
0 if address is not valid.
Return value of proto_ecpri_rmr_send_request().
References port_ip, and proto_ecpri_rmr_send_request().
Referenced by ecpri_rmr_req_func().
int stats_all_func (int argc, char ** argv, char * resp)
Reads all statistics.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0.
References stats_update_values().
int stats_all_gui_func (int argc, char ** argv, char * resp)
Reads all statistics and returns them in JSON format for GUI display.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0.
References stats_update_values().
int stats_ctrl_func (int argc, char ** argv, char * resp)
Reads control packet statistics.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0.
References stats_update_values().
int stats_func (int argc, char ** argv, char * resp)
Parses the input command string and calls a handler function (if found).
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
1 if no commands tokens found.
2 if no handler found for command.
0 otherwise.
References stats_cmds, and STATS_USAGE_STR.
int stats_help_func (int argc, char ** argv, char * resp)
Returns help strings for stats commands.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References stats_cmds.
int stats_hw_func (int argc, char ** argv, char * resp)
Reads a statistics hardware register and returns the value.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
1 if no arguments.
0 otherwise.
References STATS_API_Read_Register(), and STATS_HW_STR.
int stats_rate_func (int argc, char ** argv, char * resp)
Reads data and control packet rates.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0.
References stats_update_values().
int stats_sw_func (int argc, char ** argv, char * resp)
Dummy function, returns the help text.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0.
References STATS_SW_STR.
int stats_update_values (void)
Updates the internal status variables.
Returns
Return value of STATS_API_Read_Register() on error.
Return value of IP_API_Read_Register() on error.
Return value of IP_API_Read_Register() otherwise.
References IP_API_Read_Register(), and STATS_API_Read_Register().
Referenced by stats_all_func(), stats_all_gui_func(), stats_ctrl_func(), stats_rate_func(), and stats_user_func().
int stats_user_func (int argc, char ** argv, char * resp)
Reads user packet statistics.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0.
References stats_update_values().
int test_mesg_send_request (char * dest_addr, char * dest_port)
Sends a test message (generic data) to a remote node.
This function calls the eCPRI protocol module to format and send the message.
Parameters
[in] dest_addr IP address of remote node.
[in] dest_port IP port address of the remote node.
Returns
0 if address is not valid.
Return value of proto_ecpri_test_mesg_send().
References proto_ecpri_test_mesg_send().
Referenced by ecpri_test_mesg_func().
int tokenise_input (char * in_str, char ** cmd_tokens)
Splits the input string into an array of command tokens.
Parameters
[in] in_str Input string of space separated tokens.
[out] cmd_tokens Pointer to string array to place tokens in.
Returns
Number of tokens separated.
References MAX_NUMBER_TOKENS.
Referenced by parse_command().
int version_func (int argc, char ** argv, char * resp)
Dummy function for un-implemented "version" command.
Parameters
[in] argc Number of string arguments.
[in] argv Array of strings containg arguments.
[out] resp Pointer to string to place response text in.
Returns
0
References XROE_VER_STR.
Variable Documentation
commands_t cmds[XROE_MAX_COMMANDS]
Initial value:
= {
        {"help", XROE_HELP_STR, help_func},
        {"ecpri", ECPRI_STR, ecpri_func},
        {"ip", IP_STR, ip_func},
        {"stats", STATS_STR, stats_func},
        {"version", XROE_VER_STR, version_func},
        {"enable", XROE_ENABLE_STR, enable_func},
        {"disable", XROE_DISABLE_STR, disable_func},
        {"restart", XROE_RESTART_STR, restart_func},
        {"framing", XROE_FRAM_STR, framing_func},
        {"radio", RADIO_CTRL_STR, radio_ctrl_func},
        {NULL, NULL, NULL}
}
cmds The top-level commands handled by the command parser.
Referenced by help_func(), and parse_command().
struct register_access deframer_regs[FRAMING_DEFRAMER_REG_NUM]
Initial value:
= {
        {DEFM_DRPDEFM_DATA_PC_ID_ADDR, DEFM_DRPDEFM_DATA_PC_ID_OFFSET, DEFM_DRPDEFM_DATA_PC_ID_MASK, "data_pc_id"},
        {DEFM_DRPDEFM_CTRL_PC_ID_ADDR, DEFM_DRPDEFM_CTRL_PC_ID_OFFSET, DEFM_DRPDEFM_CTRL_PC_ID_MASK, "ctrl_pc_id"},
        {DEFM_DRPDEFM_DATA_BUFFER_STATE_LATENCY_ADDR, DEFM_DRPDEFM_DATA_BUFFER_STATE_LATENCY_OFFSET, DEFM_DRPDEFM_DATA_BUFFER_STATE_LATENCY_MASK, "dbs_latency"},
        {DEFM_DRPDEFM_DATA_BUFFER_STATE_ALIGNMENT_ADDR, DEFM_DRPDEFM_DATA_BUFFER_STATE_ALIGNMENT_OFFSET, DEFM_DRPDEFM_DATA_BUFFER_STATE_ALIGNMENT_MASK, "dbs_alignment"},
        {DEFM_DRPDEFM_DATA_BUFFER_STATE_OVERFLOW_ADDR, DEFM_DRPDEFM_DATA_BUFFER_STATE_OVERFLOW_OFFSET, DEFM_DRPDEFM_DATA_BUFFER_STATE_OVERFLOW_MASK, "dbs_overflow"},
        {DEFM_DRPDEFM_DATA_BUFFER_STATE_UNDERFLOW_ADDR, DEFM_DRPDEFM_DATA_BUFFER_STATE_UNDERFLOW_OFFSET, DEFM_DRPDEFM_DATA_BUFFER_STATE_UNDERFLOW_MASK, "dbs_underflow"},
        {DEFM_DRPDEFM_DATA_BUFFER_STATE_REGULAR_ADDR, DEFM_DRPDEFM_DATA_BUFFER_STATE_REGULAR_OFFSET, DEFM_DRPDEFM_DATA_BUFFER_STATE_REGULAR_MASK, "dbs_regular"},
        {DEFM_DRPDEFM_DATA_BUFFER_STATE_RWIN_ADDR, DEFM_DRPDEFM_DATA_BUFFER_STATE_RWIN_OFFSET, DEFM_DRPDEFM_DATA_BUFFER_STATE_RWIN_MASK, "dbs_rwin"},
        {DEFM_DRPDEFM_CTRL_BUFFER_STATE_LATENCY_ADDR, DEFM_DRPDEFM_CTRL_BUFFER_STATE_LATENCY_OFFSET, DEFM_DRPDEFM_CTRL_BUFFER_STATE_LATENCY_MASK, "cbs_latency"},
        {DEFM_DRPDEFM_CTRL_BUFFER_STATE_ALIGNMENT_ADDR, DEFM_DRPDEFM_CTRL_BUFFER_STATE_ALIGNMENT_OFFSET, DEFM_DRPDEFM_CTRL_BUFFER_STATE_ALIGNMENT_MASK, "cbs_alignment"},
        {DEFM_DRPDEFM_CTRL_BUFFER_STATE_OVERFLOW_ADDR, DEFM_DRPDEFM_CTRL_BUFFER_STATE_OVERFLOW_OFFSET, DEFM_DRPDEFM_CTRL_BUFFER_STATE_OVERFLOW_MASK, "cbs_overflow"},
        {DEFM_DRPDEFM_CTRL_BUFFER_STATE_UNDERFLOW_ADDR, DEFM_DRPDEFM_CTRL_BUFFER_STATE_UNDERFLOW_OFFSET, DEFM_DRPDEFM_CTRL_BUFFER_STATE_UNDERFLOW_MASK, "cbs_underflow"},
        {DEFM_DRPDEFM_CTRL_BUFFER_STATE_REGULAR_ADDR, DEFM_DRPDEFM_CTRL_BUFFER_STATE_REGULAR_OFFSET, DEFM_DRPDEFM_CTRL_BUFFER_STATE_REGULAR_MASK, "cbs_regular"},
        {DEFM_DRPDEFM_CTRL_BUFFER_STATE_RWIN_ADDR, DEFM_DRPDEFM_CTRL_BUFFER_STATE_RWIN_OFFSET, DEFM_DRPDEFM_CTRL_BUFFER_STATE_RWIN_MASK, "cbs_rwin"}
}
deframer_regs Register fields in the deframer.
commands_t disable_cmds[DISABLE_MAX_COMMANDS]
Initial value:
= {
        {"help", DISABLE_HELP_STR, disable_help_func},
        {"framer", DISABLE_FRAMER_STR, disable_framer_func},
        {"deframer", DISABLE_DEFRAMER_STR, disable_deframer_func},
        {NULL, NULL, NULL}
}
disable_cmds The commands handled by the disable module.
Referenced by disable_func(), and disable_help_func().
commands_t ecpri_cmds[ECPRI_MAX_COMMANDS]
Initial value:
= {
        {"help", ECPRI_HELP_STR, ecpri_help_func},
        {"rma_read", ECPRI_RMA_READ_STR, ecpri_rma_read_func},
        {"rma_write", ECPRI_RMA_WRITE_STR, ecpri_rma_write_func},
        {"owdm_req", ECPRI_OWDM_REQ_STR, ecpri_owdm_req_func},
        {"owdm_res", ECPRI_OWDM_RES_STR, ecpri_owdm_res_func},
        {"owdm_limit", ECPRI_OWDM_LIMIT_STR, ecpri_owdm_limit_func},
        {"test_mesg", ECPRI_TEST_MESG_STR, ecpri_test_mesg_func},
        {"rmr_req", ECPRI_RMR_REQ_STR, ecpri_rmr_req_func},
        {NULL, NULL, NULL}
}
ecpri_cmds The commands handled by the disable module.
Referenced by ecpri_func(), and ecpri_help_func().
commands_t enable_cmds[ENABLE_MAX_COMMANDS]
Initial value:
= {
        {"help", ENABLE_HELP_STR, enable_help_func},
        {"framer", ENABLE_FRAMER_STR, enable_framer_func},
        {"deframer", ENABLE_DEFRAMER_STR, enable_deframer_func},
        {NULL, NULL, NULL}
}
enable_cmds The commands handled by the enable module.
Referenced by enable_func(), and enable_help_func().
struct register_access framer_regs[FRAMING_FRAMER_REG_NUM]
Initial value:
= {
        {FRAM_DRPFRAM_DATA_PC_ID_ADDR, FRAM_DRPFRAM_DATA_PC_ID_OFFSET, FRAM_DRPFRAM_DATA_PC_ID_MASK, "data_pc_id"},
        {FRAM_DRPFRAM_DATA_MESSAGE_TYPE_ADDR, FRAM_DRPFRAM_DATA_MESSAGE_TYPE_OFFSET, FRAM_DRPFRAM_DATA_MESSAGE_TYPE_MASK,"data_type"},
        {FRAM_DRPFRAM_DATA_ETHERNET_PORT_ADDR, FRAM_DRPFRAM_DATA_ETHERNET_PORT_OFFSET, FRAM_DRPFRAM_DATA_ETHERNET_PORT_MASK, "data_port"},
        {FRAM_DRPFRAM_CTRL_PC_ID_ADDR, FRAM_DRPFRAM_CTRL_PC_ID_OFFSET, FRAM_DRPFRAM_CTRL_PC_ID_MASK, "ctrl_pc_id"},
        {FRAM_DRPFRAM_CTRL_MESSAGE_TYPE_ADDR, FRAM_DRPFRAM_CTRL_MESSAGE_TYPE_OFFSET, FRAM_DRPFRAM_CTRL_MESSAGE_TYPE_MASK, "ctrl_type"},
        {FRAM_DRPFRAM_CTRL_ETHERNET_PORT_ADDR, FRAM_DRPFRAM_CTRL_ETHERNET_PORT_OFFSET, FRAM_DRPFRAM_CTRL_ETHERNET_PORT_MASK, "ctrl_port"}
}
framer_regs Register fields in the framer.
commands_t framing_cmds[FRAMING_MAX_COMMANDS]
Initial value:
= {
        {"help", FRAMING_HELP_STR, framing_help_func},
        {"set_fram", FRAMING_SET_FRAM_STR, framing_set_fram_func},
        {"get_fram", FRAMING_GET_FRAM_STR, framing_get_fram_func},
        {"set_defr", FRAMING_SET_DEFR_STR, framing_set_defr_func},
        {"get_defr", FRAMING_GET_DEFR_STR, framing_get_defr_func},
        {NULL, NULL, NULL}
}
framing_cmds The commands handled by the framing module.
Referenced by framing_func(), and framing_help_func().
commands_t ip_cmds[IP_MAX_COMMANDS]
Initial value:
= {
        {"help", IP_HELP_STR, ip_help_func},
        {"peek", IP_PEEK_STR, ip_peek_func},
        {"poke", IP_POKE_STR, ip_poke_func},
        {NULL, NULL, NULL}
}
ip_cmds The commands handled by the IP module.
Referenced by ip_func(), and ip_help_func().
commands_t radio_ctrl_cmds[RADIO_MAX_COMMANDS]
Initial value:
= {
        {"help", RADIO_CTRL_HELP_STR, radio_ctrl_help_func},
        {"status", RADIO_CTRL_STATUS_STR, radio_ctrl_status_func},
        {"loopback_en", RADIO_CTRL_LOOPBACK_EN_STR, radio_ctrl_loopback_en_func},
        {"loopback_dis", RADIO_CTRL_LOOPBACK_DIS_STR, radio_ctrl_loopback_dis_func},
        {"id", RADIO_CTRL_RADIO_ID_STR, radio_ctrl_radio_id_func},
        {"gui", RADIO_CTRL_GUI_STR, radio_ctrl_gui_func},
        {"peek", RADIO_CTRL_PEEK_STR, radio_ctrl_peek_func},
        {"poke", RADIO_CTRL_POKE_STR, radio_ctrl_poke_func},
        {NULL, NULL, NULL}
}
radio_ctrl_cmds The commands handled by the radio_ctrl module.
Referenced by radio_ctrl_func(), and radio_ctrl_help_func().
commands_t restart_cmds[RESTART_MAX_COMMANDS]
Initial value:
= {
        { "help", RESTART_HELP_STR, restart_help_func },
        { "xxv", RESTART_XXV_RESET_STR, restart_xxv_func },
        { NULL, NULL, NULL }
}
restart_cmds The commands handled by the restart module.
Referenced by restart_func(), and restart_help_func().
commands_t stats_cmds[STATS_MAX_COMMANDS]
Initial value:
= {
        { "help", STATS_HELP_STR, stats_help_func },
        { "hw", STATS_HW_STR, stats_hw_func },
        { "sw", STATS_SW_STR, stats_sw_func },
        { "user", STATS_USER_STR, stats_user_func },
        { "control", STATS_CTRL_STR, stats_ctrl_func },
        { "rate", STATS_RATE_STR, stats_rate_func },
        { "all", STATS_ALL_STR, stats_all_func },
        { "gui", STATS_GUI_NUM_STR, stats_all_gui_func },
        { NULL, NULL, NULL }
}
stats_cmds The commands handled by the stats module.
Referenced by stats_func(), and stats_help_func().